name: sp500
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.0.1
  - pandas=2.3.0
  - scikit-learn=1.7.0
  - xgboost=2.1.1
  - tensorflow=2.18.1
  - matplotlib=3.10.1
  - scipy=1.15.3
  - joblib=1.5.1
  - jupyterlab=4.3.4
  - ipykernel=6.29.5
  - yfinance=0.2.57
  - pip
